# Generated by Django 5.0.6 on 2024-10-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quickstart", "0002_chatsession_chatmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="title",
            field=models.CharField(default="Untitled Session", max_length=255),
        ),
    ]
