# Generated by Django 5.0.6 on 2024-10-30 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quickstart", "0004_chatsession_is_active_alter_chatmessage_sender"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="image",
            field=models.TextField(blank=True, null=True),
        ),
    ]
