# Generated by Django 5.0.6 on 2024-11-21 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quickstart", "0005_chatmessage_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="SATQuestion",
            fields=[
                (
                    "id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                (
                    "domain",
                    models.CharField(
                        choices=[
                            (
                                "Problem-Solving and Data Analysis",
                                "Problem-Solving and Data Analysis",
                            ),
                            ("Algebra", "Algebra"),
                            ("Advanced Math", "Advanced Math"),
                            ("Geometry and Trigonometry", "Geometry and Trigonometry"),
                        ],
                        max_length=50,
                    ),
                ),
                ("question_text", models.TextField()),
                ("choices", models.JSONField()),
                ("correct_answer", models.CharField(max_length=1)),
                ("explanation", models.TextField(blank=True, null=True)),
                ("difficulty", models.CharField(max_length=20)),
                ("visuals", models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
